eggjs/schedule

agent.js, app.js, lib/load_schedule.js, test/schedule.test.js
=> fix: use absolute path for store key

app.js, test/schedule.test.js
=> fix: path in ctx

agent.js, package.json, test/fixtures/immediate/app/schedule/immediate-cron.js, test/fixtures/immediate/app/schedule/immediate-interval.js, test/fixtures/immediate/package.json, test/schedule.test.js
- 支持 `immediate` 属性, 启动后立即执行一次
=> feat: support immediate

README.md
=> doc: fix plugin.js config demo

lib/load_schedule.js, test/schedule.test.js
=> feat: export app.schedules

agent.js, test/fixtures/all/app/schedule/interval.js, test/fixtures/customType/app/schedule/custom.js, test/fixtures/dynamic/app/schedule/interval.js, test/fixtures/immediate/app/schedule/immediate-interval.js, test/fixtures/plugin/plugin/app/schedule/interval.js, test/fixtures/worker/app/schedule/interval.js, test/schedule.test.js
=> fix: start schedule after egg-ready

.autod.conf.js, .travis.yml, appveyor.yml, package.json, test/schedule.test.js
=> chore: upgrade deps and fix test

test/schedule.test.js
=> test: move app.close to afterEach

agent.js
immediate
修复 immediate 触发时机太早。
=> fix: ensure emit immediate after ready

test/schedule.test.js
=> test: sleep after runSchedule

README.md, package.json
=> fix: publish files

app.js, lib/load_schedule.js, package.json, test/fixtures/subscription/app/schedule/interval.js, test/fixtures/subscription/app/schedule/sub/cron.js, test/fixtures/subscription/config/plugin.js, test/fixtures/subscription/package.json, test/schedule.test.js
schedule can extend from Subscription which is context class
Ref https://github.com/eggjs/egg/issues/1468
=> feat: support class

package.json, test/fixtures/subscription/app/schedule/interval.js, test/fixtures/subscription/app/schedule/sub/cron.js
=> test: change to extend Subscription

app.js
related https://github.com/eggjs/egg/issues/1679
=> fix: use ctx.coreLogger to record schedule log

README.md
https://travis-ci.org/eggjs/egg/jobs/338324625
```base
#175 [404] request http://127.0.0.1:17002/zh-cn/plugins/config/config.default.js, referer http://127.0.0.1:17002/zh-cn/plugins/schedule.html
#176 [404] request http://127.0.0.1:17002/en/plugins/config/config.default.js, referer http://127.0.0.1:17002/en/plugins/schedule.html
```
=> chore: fix doctools

README.md, app.js, lib/strategy/base.js, lib/timer.js, test/schedule.test.js
- https://github.com/eggjs/egg/pull/2123
- https://github.com/eggjs/egg-schedule/pull/35#pullrequestreview-98450515
```bash
2018-02-23 15:12:18,985 INFO 96404 [Timer] /Users/tz/Workspaces/coding/github.com/eggjs/egg-schedule/node_modules/_egg-logrotator@3.0.1@egg-logrotator/app/schedule/clean_log.js next time will execute at 2018-02-24 00:00:00.000
2018-02-23 15:12:18,986 INFO 96404 [Timer] /Users/tz/Workspaces/coding/github.com/eggjs/egg-schedule/node_modules/_egg-logrotator@3.0.1@egg-logrotator/app/schedule/rotate_by_file.js next time will execute at 2018-02-24 00:00:01.000
2018-02-23 15:12:18,987 INFO 96404 [Timer] /Users/tz/Workspaces/coding/github.com/eggjs/egg-schedule/test/fixtures/all/app/schedule/sub/cron.js next time will execute at 2018-02-23 15:12:20.000
2018-02-23 …
```
=> feat: optimize logger msg

README.md, lib/load_schedule.js, test/fixtures/customDirectory/app/other-schedule/custom.js, test/fixtures/customDirectory/app/schedule/interval.js, test/fixtures/customDirectory/config/config.js, test/fixtures/customDirectory/config/plugin.js, test/fixtures/customDirectory/package.json, test/schedule.test.js
Close https://github.com/eggjs/egg/issues/3249
=> feat: support custom directory

config/config.default.js
relate: https://github.com/eggjs/egg-logger/pull/41
=> chore: use relative log path

app.js, test/fixtures/worker/app/schedule/sub/cron.js, test/schedule.test.js
https://github.com/eggjs/egg/issues/2300#issuecomment-486287852
=> fix: runSchedule should pass args

lib/load_schedule.js
=> fix: wrap task should always return promise

lib/strategy/timer.js
=> fix: should use template literal

.github/workflows/nodejs.yml, .travis.yml, app.js, appveyor.yml, package.json, test/fixtures/detect-error/app/schedule/error.js, test/fixtures/detect-error/app/schedule/fail.js, test/fixtures/detect-error/app/schedule/suc.js, test/fixtures/detect-error/package.json, test/schedule.test.js
=> fix: only reject/error detect as fail

README.md
README.MD
Updated README with some grammatical and spelling fixes.
=> docs: updated README with grammatical and spelling fixes
